import type { Metadata } from "next";
import { Toaster } from 'sonner'

import "./provider-client"
import "./globals.css";

import { GlobalLoaderProvider } from "@/components/loader/global-loader-provider";
import { GlobalLoader } from "@/components/loader/global-loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body>
        <GlobalLoaderProvider>
          <Toaster
            position="bottom-right"
            richColors
          />
          {children}
          <GlobalLoader />
        </GlobalLoaderProvider>
      </body>
    </html>
  );
}
