import type { Metadata } from "next";
import { Toaster } from 'sonner'
import "./provider-client"
import "./provider-server"
//Load styles
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="bottom-right"
          richColors
        />
        {children}
      </body>
    </html>
  );
}
